### ISSUE TITLE
Recurring sub-commands and arguments

### ISSUE THREAD

**Issue by achmielinska** [TylerTemp/docpie#4]
Hello

Is it possible to parse something like that?
```
'''
Example of program which uses [options] shortcut in pattern.

Usage:
  options_shortcut_example.py --help | --version
  options_shortcut_example.py [options] (do --after=<float> [--grace])... <port>...

Arguments:
  <port>                   give port

Generic options:
  -h --help                show this help message and exit
  --version                show version and exit
  -n, --number N           use N as a number
  -t, --timeout TIMEOUT    set timeout TIMEOUT seconds
  --apply                  apply changes to database
  -q                       operate in quiet mode

Commands:
  do                       do smth

Command options:
  --after=<float>          do smth after <float> time
  --grace                  do smth with grace
'''
```

Where `--after=<float>` is obligatory option for `do` sub-command and `<port>` can be recurring.

When I set `--after=<float>` as optional:

```
options_shortcut_example.py [options] (do [--after=<float>] [--grace])... <port>...
```

 it is parsed, but not in desired way:
```
python options_shortcut_example.py -n 6 do --after=4 'a.txt'
```
```
{'--': False,
 '--after': [],
 '--apply': False,
 '--grace': 0,
 '--help': False,
 '--number': ' 6',
 '--timeout': None,
 '--version': False,
 '-h': False,
 '-n': ' 6',
 '-q': False,
 '-t': None,
 '<port>': ['--after=4', 'a.txt'],
 'do': 1}
```
In both cases I have used `optionsfirst=True`.
Is there any way-around?

**Comment by TylerTemp** [comment]
It's a bug, thanks for reporting. 

I'll try to fix it soon.

--------------------------------

BTW, this bug in version `0.2.8` has a little different behavior:

for argv=`-n 6 do --after=4 'a.txt'`:

1.  for `(do --after=<float> [--grace])...`, with `optionfirst=True`, It raise an `--` error [online demo >>](http://docpie.comes.today/project/docpie/try/?doc=Example+of+program+which+uses+[options]+shortcut+in+pattern.%0D%0A%0D%0AUsage%3A%0D%0A++options_shortcut_example.py+--help+|+--version%0D%0A++options_shortcut_example.py+[options]+%28do+--after%3D%3Cfloat%3E+[--grace]%29...+%3Cport%3E...%0D%0A%0D%0AArguments%3A%0D%0A++%3Cport%3E+++++++++++++++++++give+port%0D%0A%0D%0AGeneric+options%3A%0D%0A++-h+--help++++++++++++++++show+this+help+message+and+exit%0D%0A++--version++++++++++++++++show+version+and+exit%0D%0A++-n%2C+--number+N+++++++++++use+N+as+a+number%0D%0A++-t%2C+--timeout+TIMEOUT++++set+timeout+TIMEOUT+seconds%0D%0A++--apply++++++++++++++++++apply+changes+to+database%0D%0A++-q+++++++++++++++++++++++operate+in+quiet+mode%0D%0A%0D%0ACommands%3A%0D%0A++do+++++++++++++++++++++++do+smth%0D%0A%0D%0ACommand+options%3A%0D%0A++--after%3D%3Cfloat%3E++++++++++do+smth+after+%3Cfloat%3E+time%0D%0A++--grace++++++++++++++++++do+smth+with+grace&argv=-n+6+do+--after%3D4+%27a.txt%27&help=true&version=&stdopt=true&attachopt=true&attachvalue=true&auto2dashes=true&name=&case_sensitive=false&optionsfirst=true&appearedonly=false)
2.  for `(do --after=<float> [--grace])...`, the result looks right. [online demo >>](http://docpie.comes.today/project/docpie/try/?doc=Example+of+program+which+uses+[options]+shortcut+in+pattern.%0D%0A%0D%0AUsage%3A%0D%0A++options_shortcut_example.py+--help+|+--version%0D%0A++options_shortcut_example.py+[options]+%28do+--after%3D%3Cfloat%3E+[--grace]%29...+%3Cport%3E...%0D%0A%0D%0AArguments%3A%0D%0A++%3Cport%3E+++++++++++++++++++give+port%0D%0A%0D%0AGeneric+options%3A%0D%0A++-h+--help++++++++++++++++show+this+help+message+and+exit%0D%0A++--version++++++++++++++++show+version+and+exit%0D%0A++-n%2C+--number+N+++++++++++use+N+as+a+number%0D%0A++-t%2C+--timeout+TIMEOUT++++set+timeout+TIMEOUT+seconds%0D%0A++--apply++++++++++++++++++apply+changes+to+database%0D%0A++-q+++++++++++++++++++++++operate+in+quiet+mode%0D%0A%0D%0ACommands%3A%0D%0A++do+++++++++++++++++++++++do+smth%0D%0A%0D%0ACommand+options%3A%0D%0A++--after%3D%3Cfloat%3E++++++++++do+smth+after+%3Cfloat%3E+time%0D%0A++--grace++++++++++++++++++do+smth+with+grace&argv=-n+6+do+--after%3D4+%27a.txt%27&help=true&version=&stdopt=true&attachopt=true&attachvalue=true&auto2dashes=true&name=&case_sensitive=false&optionsfirst=false&appearedonly=false)

        {'--': False,
         '--after': ['4'],
         '--apply': False,
         '--grace': 0,
         '--help': False,
         '--number': '6',
         '--timeout': None,
         '--version': False,
         '-h': False,
         '-n': '6',
         '-q': False,
         '-t': None,
         '<port>': ['a.txt'],
         'do': 1}

3.  for `(do [--after=<float>] [--grace])...`, with `optionsfirst=True`, same error. [online demo >>](http://docpie.comes.today/try/?doc=Usage%3A%0D%0A++++options_shortcut_example.py+[options]+%28do+[--after%3D%3Cfloat%3E]+[--grace]%29...+%3Cport%3E...%0D%0A%0D%0AArguments%3A%0D%0A++%3Cport%3E+++++++++++++++++++give+port%0D%0A%0D%0AGeneric+options%3A%0D%0A++-h+--help++++++++++++++++show+this+help+message+and+exit%0D%0A++--version++++++++++++++++show+version+and+exit%0D%0A++-n%2C+--number+N+++++++++++use+N+as+a+number%0D%0A++-t%2C+--timeout+TIMEOUT++++set+timeout+TIMEOUT+seconds%0D%0A++--apply++++++++++++++++++apply+changes+to+database%0D%0A++-q+++++++++++++++++++++++operate+in+quiet+mode%0D%0A%0D%0ACommands%3A%0D%0A++do+++++++++++++++++++++++do+smth%0D%0A%0D%0ACommand+options%3A%0D%0A++--after%3D%3Cfloat%3E++++++++++do+smth+after+%3Cfloat%3E+time%0D%0A++--grace++++++++++++++++++do+smth+with+grace&argv=-n+6+do+--after%3D4+%27a.txt%27&help=true&version=&stdopt=true&attachopt=true&attachvalue=true&auto2dashes=true&name=&case_sensitive=false&optionsfirst=true&appearedonly=false)
4.  for `(do [--after=<float>] [--grace])...`, looks currect. [online demo >>](http://docpie.comes.today/try/?doc=Usage%3A%0D%0A++++options_shortcut_example.py+[options]+%28do+[--after%3D%3Cfloat%3E]+[--grace]%29...+%3Cport%3E...%0D%0A%0D%0AArguments%3A%0D%0A++%3Cport%3E+++++++++++++++++++give+port%0D%0A%0D%0AGeneric+options%3A%0D%0A++-h+--help++++++++++++++++show+this+help+message+and+exit%0D%0A++--version++++++++++++++++show+version+and+exit%0D%0A++-n%2C+--number+N+++++++++++use+N+as+a+number%0D%0A++-t%2C+--timeout+TIMEOUT++++set+timeout+TIMEOUT+seconds%0D%0A++--apply++++++++++++++++++apply+changes+to+database%0D%0A++-q+++++++++++++++++++++++operate+in+quiet+mode%0D%0A%0D%0ACommands%3A%0D%0A++do+++++++++++++++++++++++do+smth%0D%0A%0D%0ACommand+options%3A%0D%0A++--after%3D%3Cfloat%3E++++++++++do+smth+after+%3Cfloat%3E+time%0D%0A++--grace++++++++++++++++++do+smth+with+grace&argv=-n+6+do+--after%3D4+%27a.txt%27&help=true&version=&stdopt=true&attachopt=true&attachvalue=true&auto2dashes=true&name=&case_sensitive=false&optionsfirst=false&appearedonly=false)

        {'--': False,
         '--after': ['4'],
         '--apply': False,
         '--grace': 0,
         '--help': False,
         '--number': '6',
         '--timeout': None,
         '--version': False,
         '-h': False,
         '-n': '6',
         '-q': False,
         '-t': None,
         '<port>': ['a.txt'],
         'do': 1}

**Comment by TylerTemp** [comment]
Now it should work as expected (version 0.2.9):

for argv = `prog -n 6 do --after=4 'a.txt'`

for `options_shortcut_example.py [options] (do --after=<float> [--grace])... <port>...`

1.  with `optionsfirst=True` it failes, because after the first non-option(`do`) the following elements will be parsed as command/argument, which makes the `--after`(required) unmatched. [demo >>](http://docpie.comes.today/project/docpie/try/?doc=Example+of+program+which+uses+[options]+shortcut+in+pattern.%0D%0A%0D%0AUsage%3A%0D%0A++options_shortcut_example.py+--help+|+--version%0D%0A++options_shortcut_example.py+[options]+%28do+--after%3D%3Cfloat%3E+[--grace]%29...+%3Cport%3E...%0D%0A%0D%0AArguments%3A%0D%0A++%3Cport%3E+++++++++++++++++++give+port%0D%0A%0D%0AGeneric+options%3A%0D%0A++-h+--help++++++++++++++++show+this+help+message+and+exit%0D%0A++--version++++++++++++++++show+version+and+exit%0D%0A++-n%2C+--number+N+++++++++++use+N+as+a+number%0D%0A++-t%2C+--timeout+TIMEOUT++++set+timeout+TIMEOUT+seconds%0D%0A++--apply++++++++++++++++++apply+changes+to+database%0D%0A++-q+++++++++++++++++++++++operate+in+quiet+mode%0D%0A%0D%0ACommands%3A%0D%0A++do+++++++++++++++++++++++do+smth%0D%0A%0D%0ACommand+options%3A%0D%0A++--after%3D%3Cfloat%3E++++++++++do+smth+after+%3Cfloat%3E+time%0D%0A++--grace++++++++++++++++++do+smth+with+grace&argv=-n+6+do+--after%3D4+%27a.txt%27&help=true&version=&stdopt=true&attachopt=true&attachvalue=true&auto2dashes=true&name=&case_sensitive=false&optionsfirst=true&appearedonly=false)
2.  with `optionsfirst=False` it gives the expected result: [demo >>](http://docpie.comes.today/project/docpie/try/?doc=Example+of+program+which+uses+[options]+shortcut+in+pattern.%0D%0A%0D%0AUsage%3A%0D%0A++options_shortcut_example.py+--help+|+--version%0D%0A++options_shortcut_example.py+[options]+%28do+--after%3D%3Cfloat%3E+[--grace]%29...+%3Cport%3E...%0D%0A%0D%0AArguments%3A%0D%0A++%3Cport%3E+++++++++++++++++++give+port%0D%0A%0D%0AGeneric+options%3A%0D%0A++-h+--help++++++++++++++++show+this+help+message+and+exit%0D%0A++--version++++++++++++++++show+version+and+exit%0D%0A++-n%2C+--number+N+++++++++++use+N+as+a+number%0D%0A++-t%2C+--timeout+TIMEOUT++++set+timeout+TIMEOUT+seconds%0D%0A++--apply++++++++++++++++++apply+changes+to+database%0D%0A++-q+++++++++++++++++++++++operate+in+quiet+mode%0D%0A%0D%0ACommands%3A%0D%0A++do+++++++++++++++++++++++do+smth%0D%0A%0D%0ACommand+options%3A%0D%0A++--after%3D%3Cfloat%3E++++++++++do+smth+after+%3Cfloat%3E+time%0D%0A++--grace++++++++++++++++++do+smth+with+grace&argv=-n+6+do+--after%3D4+%27a.txt%27&help=true&version=&stdopt=true&attachopt=true&attachvalue=true&auto2dashes=true&name=&case_sensitive=false&optionsfirst=false&appearedonly=false)

        {'--': False,
         '--after': ['4'],
         '--apply': False,
         '--grace': 0,
         '--help': False,
         '--number': '6',
         '--timeout': None,
         '--version': False,
         '-h': False,
         '-n': '6',
         '-q': False,
         '-t': None,
         '<port>': ['a.txt'],
         'do': 1}

for `options_shortcut_example.py [options] (do [--after=<float>] [--grace])... <port>...`

1.  with `optionsfirst=True`, `--after=4` will be parsed as command/argument [demo >>](http://docpie.comes.today/try/?doc=Usage%3A%0D%0A++++options_shortcut_example.py+[options]+%28do+[--after%3D%3Cfloat%3E]+[--grace]%29...+%3Cport%3E...%0D%0A%0D%0AArguments%3A%0D%0A++%3Cport%3E+++++++++++++++++++give+port%0D%0A%0D%0AGeneric+options%3A%0D%0A++-h+--help++++++++++++++++show+this+help+message+and+exit%0D%0A++--version++++++++++++++++show+version+and+exit%0D%0A++-n%2C+--number+N+++++++++++use+N+as+a+number%0D%0A++-t%2C+--timeout+TIMEOUT++++set+timeout+TIMEOUT+seconds%0D%0A++--apply++++++++++++++++++apply+changes+to+database%0D%0A++-q+++++++++++++++++++++++operate+in+quiet+mode%0D%0A%0D%0ACommands%3A%0D%0A++do+++++++++++++++++++++++do+smth%0D%0A%0D%0ACommand+options%3A%0D%0A++--after%3D%3Cfloat%3E++++++++++do+smth+after+%3Cfloat%3E+time%0D%0A++--grace++++++++++++++++++do+smth+with+grace&argv=-n+6+do+--after%3D4+%27a.txt%27&help=true&version=&stdopt=true&attachopt=true&attachvalue=true&auto2dashes=true&name=&case_sensitive=false&optionsfirst=true&appearedonly=false)

        {'--': False,
         '--after': [],
         '--apply': False,
         '--grace': 0,
         '--help': False,
         '--number': '6',
         '--timeout': None,
         '--version': False,
         '-h': False,
         '-n': '6',
         '-q': False,
         '-t': None,
         '<port>': ['--after=4', 'a.txt'],
         'do': 1}

2.  with `optionsfirst=False`, same as the first `2.` [demo >>](http://docpie.comes.today/try/?doc=Usage%3A%0D%0A++++options_shortcut_example.py+[options]+%28do+[--after%3D%3Cfloat%3E]+[--grace]%29...+%3Cport%3E...%0D%0A%0D%0AArguments%3A%0D%0A++%3Cport%3E+++++++++++++++++++give+port%0D%0A%0D%0AGeneric+options%3A%0D%0A++-h+--help++++++++++++++++show+this+help+message+and+exit%0D%0A++--version++++++++++++++++show+version+and+exit%0D%0A++-n%2C+--number+N+++++++++++use+N+as+a+number%0D%0A++-t%2C+--timeout+TIMEOUT++++set+timeout+TIMEOUT+seconds%0D%0A++--apply++++++++++++++++++apply+changes+to+database%0D%0A++-q+++++++++++++++++++++++operate+in+quiet+mode%0D%0A%0D%0ACommands%3A%0D%0A++do+++++++++++++++++++++++do+smth%0D%0A%0D%0ACommand+options%3A%0D%0A++--after%3D%3Cfloat%3E++++++++++do+smth+after+%3Cfloat%3E+time%0D%0A++--grace++++++++++++++++++do+smth+with+grace&argv=-n+6+do+--after%3D4+%27a.txt%27&help=true&version=&stdopt=true&attachopt=true&attachvalue=true&auto2dashes=true&name=&case_sensitive=false&optionsfirst=false&appearedonly=false)


----------

Thanks for reporting.
