### ISSUE TITLE
Issue with optional this | or | that

### ISSUE THREAD

**Issue by pborglin** [TylerTemp/docpie#5]
Hi! I was using your package but it does not work as expected. My `__doc__`:

```
Usage: pie.py [--aa=AA|--bb=BB] --cc=CC
```

But when I give argv as: 

```
--bb B --cc C
```

it give the result:

```
Usage: pie.py [--aa=AA|--bb=BB] --cc=CC
```
Expected result would be to get B for bb parameter and CC for cc parameter.
(It works if -aa is entered with a parameter)
Bug? Or me doing wrong?

`docpie` version: 0.3.3 / Tue Jun  7 09:26:44 2016

Here is the [online demo](http://docpie.comes.today/try/?doc=Usage%3A+pie.py+%5B--aa%3DAA%7C--bb%3DBB%5D+--cc%3DCC&argv=--bb+B+--cc+C&run=on&help=on&stdopt=on&attachopt=on&attachvalue=on&auto2dashes=on)

**Comment by TylerTemp** [comment]
Thx for reporting this bug.

This bug is fixed in `0.3.5`. New version has been updated to [github/master](https://github.com/TylerTemp/docpie) released to [pypi](https://pypi.python.org/pypi/docpie),
updated to [online demo](http://docpie.comes.today/try/?doc=Usage%3A+pie.py+%5B--aa%3DAA%7C--bb%3DBB%5D+--cc%3DCC&argv=--bb+B+--cc+C&run=on&help=on&stdopt=on&attachopt=on&attachvalue=on&auto2dashes=on)

Feel free to re-open this issue if this problem still presences.
