### ISSUE TITLE
Either choice within an either choice

### ISSUE THREAD

**Issue by pborglin** [TylerTemp/docpie#6]
Hi!  
I was using your package but it does not work as I expected. My `__doc__`:

```
usage: pie.py [--aa=AA|[--bb=BB | --cc=CC]]
```

But when I give argv as: 

```
--aa
```

it give the result:

```
'Either' object has no attribute 'push_option_ahead'
```

Do not know if it is a bug or something that should not be supported?
Would be really nice if you could have the option to either choose aa and if  you do not want that, you can choose between between bb and cc. Need it for my CLI implementation at least.

Thanks! Also thanks for the last correction you made on the issue I put. Really helped :-)

`docpie` version: 0.3.5 / Thu Jun 15 10:41:24 2017

Here is the [online demo](http://docpie.comes.today/try/?doc=usage%3A+pie.py+%5B--aa%3DAA%7C%5B--bb%3DBB+%7C+--cc%3DCC%5D%5D&argv=--aa&run=on&help=on&stdopt=on&attachopt=on&attachvalue=on&auto2dashes=on)

**Comment by TylerTemp** [comment]
This is fixed in github master. The new version will be released soon.

This bug is now in the default [unit test](https://github.com/TylerTemp/docpie/commit/0d0c82d9f9d5cc976add351525e7e35a7dd479bb#diff-fc535f0e680b75af6e091a3ddb69f33eR2519). You can test it by yourself though `python -m docpie.test` or `python setup.py test` with the master branch of docpie's github.

Thanks again for submitting this **critical** bug.

Feel free to re-open this issue if this problem still presences.
